name: pipeline_env
dependencies:
        - schrodinger::pymol=2.4.1
        - pandas=1.4.3
        - pathlib=1.0.1
        - numpy<1.24.0
        - matplotlib
        - conda-forge::biopython
        - conda-forge::biopandas
        - conda-forge::configargparse